image: hub.butterfly.com.au/deployer:aws-eb-1.0
stages:
  - deploy

deploy prod:
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: $PROD_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $PROD_AWS_SECRET_ACCESS_KEY
    AWS_REGION: $PROD_AWS_REGION
    AWS_EC2_KEYNAME: $PROD_AWS_EC2_KEYNAME
    AWS_EB_PLATFORM_CONFIGURATION: $PROD_AWS_EB_PLATFORM_CONFIGURATION
    AWS_EB_ENVIRONMENT: $PROD_AWS_EB_ENVIRONMENT
    AWS_EB_APPLICATION_NAME: $PROD_AWS_EB_APPLICATION_NAME
  script:
  - aws-configurator
  - eb-app-switcher $AWS_EB_APPLICATION_NAME
  - eb deploy $AWS_EB_ENVIRONMENT -l $AWS_EB_ENVIRONMENT-$CI_COMMIT_SHA
  only:
    - master
  when: manual

deploy staging:
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: $STAGING_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $STAGING_AWS_SECRET_ACCESS_KEY
    AWS_REGION: $STAGING_AWS_REGION
    AWS_EC2_KEYNAME: $STAGING_AWS_EC2_KEYNAME 
    AWS_EB_PLATFORM_CONFIGURATION: $STAGING_AWS_EB_PLATFORM_CONFIGURATION
    AWS_EB_ENVIRONMENT: $STAGING_AWS_EB_ENVIRONMENT
    AWS_EB_APPLICATION_NAME: $STAGING_AWS_EB_APPLICATION_NAME
  script:
  - aws-configurator
  - eb-app-switcher $AWS_EB_APPLICATION_NAME
  - eb deploy $AWS_EB_ENVIRONMENT -l $AWS_EB_ENVIRONMENT-$CI_COMMIT_SHA
  only:
    - staging

deploy qa:
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: $QA_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $QA_AWS_SECRET_ACCESS_KEY
    AWS_REGION: $QA_AWS_REGION
    AWS_EC2_KEYNAME: $QA_AWS_EC2_KEYNAME
    AWS_EB_PLATFORM_CONFIGURATION: $QA_AWS_EB_PLATFORM_CONFIGURATION
    AWS_EB_ENVIRONMENT: $QA_AWS_EB_ENVIRONMENT
    AWS_EB_APPLICATION_NAME: $QA_AWS_EB_APPLICATION_NAME
  script:
  - aws-configurator
  - eb-app-switcher $AWS_EB_APPLICATION_NAME
  - eb deploy $AWS_EB_ENVIRONMENT -l $AWS_EB_ENVIRONMENT-$CI_COMMIT_SHA
  only:
    - qa
   
